### ISSUE TITLE
Issues with current version of drawsvg (2.x)

### ISSUE THREAD

**Issue by haiyangkehoe** [rghs/sedlog-maker#1]
drawsvg 2.x reverses the y coordinate system (increases down instead of up), resulting in plots that resist geologists' convention (see attached example). I found the easiest fix is installing drawSvg 1.x with the following command:

    pip install drawSvg~=1.9

If sedlog-maker is updated to support the new coordinate system in drawsvg 2.x, note changes in naming conventions (e.g., drawSvg to drawsvg and d.saveSvg to d.save_svg). For more information, see "Upgrading from version 1.x" here: https://pypi.org/project/drawsvg/

Also suggest including version numbers of required python modules in the README.
![broken_log](https://github.com/rghs/sedlog-maker/assets/12374870/d60fe0d5-ae5b-4c77-982b-82b605d6bab4)

**Comment by rghs** [comment]
I'll update the readme to recommend the older library. Will probably try to fix the coords issue to use the SVG standard at some point too but it's admittedly not a priority.

**Comment by rghs** [comment]
Can't really afford the time to fix this issue right now - working on a replacement coming soon(TM)
